# Generated by Django 4.0 on 2021-12-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
